/**
 * Axis & Allies 1942 2nd Edition — canonical map data.
 *
 * Contains every territory/sea-zone with its owner, IPC value,
 * adjacencies, and whether it has a starting Industrial Complex.
 */

import { PowerName, TerritoryType } from "./enums.js";

export interface TerritoryData {
  key: string;
  name: string;
  type: TerritoryType;
  /** Starting controller (null = neutral/unowned at game start) */
  startingController: PowerName | null;
  /** IPC value collected when controlled (land only; sea = 0) */
  ipcValue: number;
  /** Adjacent territory keys */
  adjacencies: string[];
  /** True if an Industrial Complex starts here */
  hasFactory: boolean;
}

export interface StartingUnit {
  territoryKey: string;
  power: PowerName;
  type: string; // UnitType string values
  quantity: number;
}

// ─── Territory definitions ────────────────────────────────────────────────────

export const TERRITORIES: TerritoryData[] = [
  // ── USSR ──────────────────────────────────────────────────────────────────
  {
    key: "russia",
    name: "Russia",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 8,
    adjacencies: ["karelia", "caucasus", "kazakh", "novosibirsk", "evenki", "yakut", "buryatia"],
    hasFactory: true,
  },
  {
    key: "karelia",
    name: "Karelia S.S.R.",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 2,
    adjacencies: ["russia", "finland", "norway", "archangel", "sz_5"],
    hasFactory: true,
  },
  {
    key: "ukraine",
    name: "Ukraine S.S.R.",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 2,
    adjacencies: ["russia", "caucasus", "belorussia", "eastern_europe", "romania"],
    hasFactory: false,
  },
  {
    key: "belorussia",
    name: "Belorussia",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 1,
    adjacencies: ["russia", "ukraine", "eastern_europe", "karelia", "baltic_states"],
    hasFactory: false,
  },
  {
    key: "baltic_states",
    name: "Baltic States",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 1,
    adjacencies: ["karelia", "belorussia", "eastern_europe", "finland"],
    hasFactory: false,
  },
  {
    key: "caucasus",
    name: "Caucasus",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 4,
    adjacencies: ["russia", "ukraine", "persia", "sz_29"],
    hasFactory: true,
  },
  {
    key: "kazakh",
    name: "Kazakh S.S.R.",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 2,
    adjacencies: ["russia", "caucasus", "persia", "india", "novosibirsk"],
    hasFactory: false,
  },
  {
    key: "novosibirsk",
    name: "Novosibirsk",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 1,
    adjacencies: ["russia", "kazakh", "evenki", "buryatia"],
    hasFactory: false,
  },
  {
    key: "evenki",
    name: "Evenki National Okrug",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 0,
    adjacencies: ["russia", "novosibirsk", "yakut", "buryatia"],
    hasFactory: false,
  },
  {
    key: "yakut",
    name: "Yakut S.S.R.",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 0,
    adjacencies: ["russia", "evenki", "buryatia"],
    hasFactory: false,
  },
  {
    key: "buryatia",
    name: "Buryatia S.S.R.",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 0,
    adjacencies: ["russia", "novosibirsk", "evenki", "yakut", "manchuria"],
    hasFactory: false,
  },
  {
    key: "archangel",
    name: "Archangel",
    type: TerritoryType.LAND,
    startingController: PowerName.USSR,
    ipcValue: 1,
    adjacencies: ["karelia", "russia"],
    hasFactory: false,
  },

  // ── GERMANY ────────────────────────────────────────────────────────────────
  {
    key: "germany",
    name: "Germany",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 10,
    adjacencies: ["western_europe", "southern_europe", "poland", "sz_5"],
    hasFactory: true,
  },
  {
    key: "western_europe",
    name: "Western Europe",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 6,
    adjacencies: ["germany", "southern_europe", "france", "sz_5", "sz_7"],
    hasFactory: true,
  },
  {
    key: "southern_europe",
    name: "Southern Europe",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 4,
    adjacencies: ["germany", "western_europe", "poland", "romania", "sz_15"],
    hasFactory: true,
  },
  {
    key: "poland",
    name: "Poland",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 2,
    adjacencies: ["germany", "southern_europe", "eastern_europe", "belorussia", "baltic_states"],
    hasFactory: false,
  },
  {
    key: "eastern_europe",
    name: "Eastern Europe",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 2,
    adjacencies: ["poland", "ukraine", "belorussia", "southern_europe", "romania", "baltic_states"],
    hasFactory: false,
  },
  {
    key: "norway",
    name: "Norway",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 2,
    adjacencies: ["karelia", "finland", "sz_5"],
    hasFactory: false,
  },
  {
    key: "finland",
    name: "Finland",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 1,
    adjacencies: ["karelia", "norway", "baltic_states"],
    hasFactory: false,
  },
  {
    key: "france",
    name: "France",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 6,
    adjacencies: ["western_europe", "sz_7"],
    hasFactory: false,
  },
  {
    key: "romania",
    name: "Romania & Bulgaria",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 3,
    adjacencies: ["ukraine", "eastern_europe", "southern_europe", "sz_15"],
    hasFactory: false,
  },
  {
    key: "libya",
    name: "Libya",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 1,
    adjacencies: ["egypt", "algeria", "sz_15"],
    hasFactory: false,
  },

  // ── UK ─────────────────────────────────────────────────────────────────────
  {
    key: "uk",
    name: "United Kingdom",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 8,
    adjacencies: ["sz_2", "sz_7"],
    hasFactory: true,
  },
  {
    key: "egypt",
    name: "Egypt",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 2,
    adjacencies: ["libya", "trans_jordan", "anglo_egypt_sudan", "sz_15"],
    hasFactory: false,
  },
  {
    key: "trans_jordan",
    name: "Trans-Jordan",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 1,
    adjacencies: ["egypt", "persia", "sz_29"],
    hasFactory: false,
  },
  {
    key: "persia",
    name: "Persia",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 1,
    adjacencies: ["caucasus", "kazakh", "india", "trans_jordan", "sz_29"],
    hasFactory: false,
  },
  {
    key: "india",
    name: "India",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 3,
    adjacencies: ["kazakh", "persia", "burma", "sz_39"],
    hasFactory: true,
  },
  {
    key: "burma",
    name: "Burma",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 1,
    adjacencies: ["india", "yunnan", "sz_39"],
    hasFactory: false,
  },
  {
    key: "australia",
    name: "Australia",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 2,
    adjacencies: ["sz_54", "sz_62"],
    hasFactory: false,
  },
  {
    key: "south_africa",
    name: "South Africa",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 2,
    adjacencies: ["rhodesia", "sz_39"],
    hasFactory: false,
  },
  {
    key: "anglo_egypt_sudan",
    name: "Anglo-Egypt Sudan",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 0,
    adjacencies: ["egypt", "ethiopia", "rhodesia"],
    hasFactory: false,
  },
  {
    key: "rhodesia",
    name: "Rhodesia",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 0,
    adjacencies: ["anglo_egypt_sudan", "south_africa", "ethiopia"],
    hasFactory: false,
  },
  {
    key: "ethiopia",
    name: "Ethiopia",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY, // Italian-held
    ipcValue: 1,
    adjacencies: ["anglo_egypt_sudan", "rhodesia"],
    hasFactory: false,
  },
  {
    key: "algeria",
    name: "Algeria",
    type: TerritoryType.LAND,
    startingController: PowerName.GERMANY,
    ipcValue: 0,
    adjacencies: ["libya", "sz_14"],
    hasFactory: false,
  },

  // ── JAPAN ──────────────────────────────────────────────────────────────────
  {
    key: "japan",
    name: "Japan",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 8,
    adjacencies: ["sz_59", "sz_60"],
    hasFactory: true,
  },
  {
    key: "manchuria",
    name: "Manchuria",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 3,
    adjacencies: ["buryatia", "korea", "china", "sz_60"],
    hasFactory: false,
  },
  {
    key: "korea",
    name: "Korea",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 2,
    adjacencies: ["manchuria", "sz_59"],
    hasFactory: false,
  },
  {
    key: "french_indo_china",
    name: "French Indo-China / Thailand",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 2,
    adjacencies: ["yunnan", "burma", "malaya", "sz_44", "sz_36"],
    hasFactory: false,
  },
  {
    key: "malaya",
    name: "Malaya",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 1,
    adjacencies: ["french_indo_china", "sz_44"],
    hasFactory: false,
  },
  {
    key: "philippine_islands",
    name: "Philippine Islands",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 3,
    adjacencies: ["sz_44", "sz_36"],
    hasFactory: false,
  },
  {
    key: "dutch_east_indies",
    name: "Dutch East Indies",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 4,
    adjacencies: ["sz_44", "sz_54"],
    hasFactory: false,
  },
  {
    key: "borneo",
    name: "Borneo",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 3,
    adjacencies: ["sz_44", "sz_36"],
    hasFactory: false,
  },
  {
    key: "new_guinea",
    name: "New Guinea",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 1,
    adjacencies: ["sz_54", "sz_46"],
    hasFactory: false,
  },
  {
    key: "wake_island",
    name: "Wake Island",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 1,
    adjacencies: ["sz_55"],
    hasFactory: false,
  },
  {
    key: "china",
    name: "China",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 2,
    adjacencies: ["manchuria", "yunnan", "india", "kazakh"],
    hasFactory: false,
  },
  {
    key: "yunnan",
    name: "Yunnan",
    type: TerritoryType.LAND,
    startingController: PowerName.JAPAN,
    ipcValue: 1,
    adjacencies: ["china", "burma", "french_indo_china"],
    hasFactory: false,
  },

  // ── USA ────────────────────────────────────────────────────────────────────
  {
    key: "eastern_us",
    name: "Eastern United States",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 12,
    adjacencies: ["central_us", "sz_101", "sz_7"],
    hasFactory: true,
  },
  {
    key: "central_us",
    name: "Central United States",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 6,
    adjacencies: ["eastern_us", "western_us"],
    hasFactory: false,
  },
  {
    key: "western_us",
    name: "Western United States",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 10,
    adjacencies: ["central_us", "alaska", "sz_10", "sz_55"],
    hasFactory: true,
  },
  {
    key: "alaska",
    name: "Alaska",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 2,
    adjacencies: ["western_us", "sz_10"],
    hasFactory: false,
  },
  {
    key: "hawaii",
    name: "Hawaiian Islands",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 1,
    adjacencies: ["sz_26"],
    hasFactory: false,
  },
  {
    key: "midway",
    name: "Midway",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 1,
    adjacencies: ["sz_26", "sz_55"],
    hasFactory: false,
  },
  {
    key: "west_indies",
    name: "West Indies",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 1,
    adjacencies: ["sz_101"],
    hasFactory: false,
  },
  {
    key: "brazil",
    name: "Brazil",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 3,
    adjacencies: ["mexico", "sz_101", "sz_86"],
    hasFactory: false,
  },
  {
    key: "mexico",
    name: "Mexico",
    type: TerritoryType.LAND,
    startingController: PowerName.USA,
    ipcValue: 0,
    adjacencies: ["western_us", "central_us", "brazil"],
    hasFactory: false,
  },

  // ── NEUTRAL / MISC ─────────────────────────────────────────────────────────
  {
    key: "greenland",
    name: "Greenland",
    type: TerritoryType.LAND,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["sz_5", "sz_101"],
    hasFactory: false,
  },
  {
    key: "iceland",
    name: "Iceland",
    type: TerritoryType.LAND,
    startingController: PowerName.UK,
    ipcValue: 0,
    adjacencies: ["sz_2", "sz_5"],
    hasFactory: false,
  },

  // ── SEA ZONES ─────────────────────────────────────────────────────────────
  {
    key: "sz_2",
    name: "Sea Zone 2",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["uk", "iceland", "sz_5", "sz_7"],
    hasFactory: false,
  },
  {
    key: "sz_5",
    name: "Sea Zone 5",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["karelia", "norway", "germany", "sz_2", "sz_7", "sz_8"],
    hasFactory: false,
  },
  {
    key: "sz_7",
    name: "Sea Zone 7",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["uk", "france", "western_europe", "sz_2", "sz_5", "sz_8", "sz_14"],
    hasFactory: false,
  },
  {
    key: "sz_8",
    name: "Sea Zone 8",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["sz_5", "sz_7", "sz_14"],
    hasFactory: false,
  },
  {
    key: "sz_10",
    name: "Sea Zone 10",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["western_us", "alaska", "sz_55"],
    hasFactory: false,
  },
  {
    key: "sz_14",
    name: "Sea Zone 14",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["algeria", "sz_7", "sz_8", "sz_15"],
    hasFactory: false,
  },
  {
    key: "sz_15",
    name: "Sea Zone 15",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["southern_europe", "romania", "libya", "egypt", "sz_14"],
    hasFactory: false,
  },
  {
    key: "sz_26",
    name: "Sea Zone 26",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["hawaii", "midway", "sz_55"],
    hasFactory: false,
  },
  {
    key: "sz_29",
    name: "Sea Zone 29",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["caucasus", "trans_jordan", "persia", "india", "sz_39"],
    hasFactory: false,
  },
  {
    key: "sz_36",
    name: "Sea Zone 36",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["french_indo_china", "philippine_islands", "borneo", "sz_44"],
    hasFactory: false,
  },
  {
    key: "sz_39",
    name: "Sea Zone 39",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["india", "burma", "south_africa", "sz_29", "sz_44", "sz_54"],
    hasFactory: false,
  },
  {
    key: "sz_44",
    name: "Sea Zone 44",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["french_indo_china", "malaya", "philippine_islands", "dutch_east_indies", "borneo", "sz_36", "sz_39", "sz_54"],
    hasFactory: false,
  },
  {
    key: "sz_46",
    name: "Sea Zone 46",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["new_guinea", "sz_54", "sz_55"],
    hasFactory: false,
  },
  {
    key: "sz_54",
    name: "Sea Zone 54",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["australia", "dutch_east_indies", "new_guinea", "sz_39", "sz_44", "sz_46"],
    hasFactory: false,
  },
  {
    key: "sz_55",
    name: "Sea Zone 55",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["western_us", "wake_island", "midway", "sz_10", "sz_26", "sz_46", "sz_59"],
    hasFactory: false,
  },
  {
    key: "sz_59",
    name: "Sea Zone 59",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["japan", "korea", "sz_55", "sz_60"],
    hasFactory: false,
  },
  {
    key: "sz_60",
    name: "Sea Zone 60",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["japan", "manchuria", "sz_59"],
    hasFactory: false,
  },
  {
    key: "sz_86",
    name: "Sea Zone 86",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["brazil", "sz_101"],
    hasFactory: false,
  },
  {
    key: "sz_101",
    name: "Sea Zone 101",
    type: TerritoryType.SEA,
    startingController: null,
    ipcValue: 0,
    adjacencies: ["eastern_us", "west_indies", "brazil", "greenland", "sz_2", "sz_7", "sz_86"],
    hasFactory: false,
  },
];

// Lookup map keyed by territory key
export const TERRITORY_MAP: Map<string, TerritoryData> = new Map(
  TERRITORIES.map((t) => [t.key, t])
);

// ─── Starting unit placements ─────────────────────────────────────────────────

export const STARTING_UNITS: StartingUnit[] = [
  // ── USSR ──────────────────────────────────────────────────────────────────
  { territoryKey: "russia", power: PowerName.USSR, type: "INFANTRY", quantity: 3 },
  { territoryKey: "russia", power: PowerName.USSR, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "russia", power: PowerName.USSR, type: "TANK", quantity: 1 },
  { territoryKey: "russia", power: PowerName.USSR, type: "FIGHTER", quantity: 1 },
  { territoryKey: "russia", power: PowerName.USSR, type: "AA_GUN", quantity: 1 },
  { territoryKey: "russia", power: PowerName.USSR, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "karelia", power: PowerName.USSR, type: "INFANTRY", quantity: 4 },
  { territoryKey: "karelia", power: PowerName.USSR, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "karelia", power: PowerName.USSR, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "ukraine", power: PowerName.USSR, type: "INFANTRY", quantity: 4 },
  { territoryKey: "ukraine", power: PowerName.USSR, type: "TANK", quantity: 1 },
  { territoryKey: "ukraine", power: PowerName.USSR, type: "AA_GUN", quantity: 1 },
  { territoryKey: "belorussia", power: PowerName.USSR, type: "INFANTRY", quantity: 2 },
  { territoryKey: "baltic_states", power: PowerName.USSR, type: "INFANTRY", quantity: 2 },
  { territoryKey: "caucasus", power: PowerName.USSR, type: "INFANTRY", quantity: 3 },
  { territoryKey: "caucasus", power: PowerName.USSR, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "archangel", power: PowerName.USSR, type: "INFANTRY", quantity: 1 },

  // ── GERMANY ────────────────────────────────────────────────────────────────
  { territoryKey: "germany", power: PowerName.GERMANY, type: "INFANTRY", quantity: 3 },
  { territoryKey: "germany", power: PowerName.GERMANY, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "germany", power: PowerName.GERMANY, type: "TANK", quantity: 1 },
  { territoryKey: "germany", power: PowerName.GERMANY, type: "FIGHTER", quantity: 2 },
  { territoryKey: "germany", power: PowerName.GERMANY, type: "BOMBER", quantity: 1 },
  { territoryKey: "germany", power: PowerName.GERMANY, type: "AA_GUN", quantity: 1 },
  { territoryKey: "germany", power: PowerName.GERMANY, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "western_europe", power: PowerName.GERMANY, type: "INFANTRY", quantity: 3 },
  { territoryKey: "western_europe", power: PowerName.GERMANY, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "western_europe", power: PowerName.GERMANY, type: "AA_GUN", quantity: 1 },
  { territoryKey: "western_europe", power: PowerName.GERMANY, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "southern_europe", power: PowerName.GERMANY, type: "INFANTRY", quantity: 2 },
  { territoryKey: "southern_europe", power: PowerName.GERMANY, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "southern_europe", power: PowerName.GERMANY, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "poland", power: PowerName.GERMANY, type: "INFANTRY", quantity: 2 },
  { territoryKey: "eastern_europe", power: PowerName.GERMANY, type: "INFANTRY", quantity: 3 },
  { territoryKey: "eastern_europe", power: PowerName.GERMANY, type: "TANK", quantity: 2 },
  { territoryKey: "norway", power: PowerName.GERMANY, type: "INFANTRY", quantity: 2 },
  { territoryKey: "finland", power: PowerName.GERMANY, type: "INFANTRY", quantity: 2 },
  { territoryKey: "france", power: PowerName.GERMANY, type: "INFANTRY", quantity: 2 },
  { territoryKey: "libya", power: PowerName.GERMANY, type: "INFANTRY", quantity: 3 },
  { territoryKey: "libya", power: PowerName.GERMANY, type: "TANK", quantity: 2 },
  { territoryKey: "sz_5", power: PowerName.GERMANY, type: "SUBMARINE", quantity: 1 },
  { territoryKey: "sz_5", power: PowerName.GERMANY, type: "DESTROYER", quantity: 1 },
  { territoryKey: "sz_15", power: PowerName.GERMANY, type: "SUBMARINE", quantity: 1 },
  { territoryKey: "sz_15", power: PowerName.GERMANY, type: "DESTROYER", quantity: 1 },
  { territoryKey: "sz_15", power: PowerName.GERMANY, type: "BATTLESHIP", quantity: 1 },
  { territoryKey: "sz_7", power: PowerName.GERMANY, type: "SUBMARINE", quantity: 2 },

  // ── UK ─────────────────────────────────────────────────────────────────────
  { territoryKey: "uk", power: PowerName.UK, type: "INFANTRY", quantity: 3 },
  { territoryKey: "uk", power: PowerName.UK, type: "FIGHTER", quantity: 1 },
  { territoryKey: "uk", power: PowerName.UK, type: "BOMBER", quantity: 1 },
  { territoryKey: "uk", power: PowerName.UK, type: "AA_GUN", quantity: 1 },
  { territoryKey: "uk", power: PowerName.UK, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "egypt", power: PowerName.UK, type: "INFANTRY", quantity: 3 },
  { territoryKey: "egypt", power: PowerName.UK, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "egypt", power: PowerName.UK, type: "TANK", quantity: 1 },
  { territoryKey: "egypt", power: PowerName.UK, type: "FIGHTER", quantity: 1 },
  { territoryKey: "trans_jordan", power: PowerName.UK, type: "INFANTRY", quantity: 1 },
  { territoryKey: "india", power: PowerName.UK, type: "INFANTRY", quantity: 3 },
  { territoryKey: "india", power: PowerName.UK, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "india", power: PowerName.UK, type: "FIGHTER", quantity: 1 },
  { territoryKey: "india", power: PowerName.UK, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "burma", power: PowerName.UK, type: "INFANTRY", quantity: 1 },
  { territoryKey: "australia", power: PowerName.UK, type: "INFANTRY", quantity: 2 },
  { territoryKey: "australia", power: PowerName.UK, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "south_africa", power: PowerName.UK, type: "INFANTRY", quantity: 2 },
  { territoryKey: "sz_2", power: PowerName.UK, type: "BATTLESHIP", quantity: 1 },
  { territoryKey: "sz_2", power: PowerName.UK, type: "CARRIER", quantity: 1 },
  { territoryKey: "sz_2", power: PowerName.UK, type: "FIGHTER", quantity: 1 },
  { territoryKey: "sz_7", power: PowerName.UK, type: "DESTROYER", quantity: 1 },
  { territoryKey: "sz_7", power: PowerName.UK, type: "TRANSPORT", quantity: 1 },
  { territoryKey: "sz_15", power: PowerName.UK, type: "DESTROYER", quantity: 1 },

  // ── JAPAN ──────────────────────────────────────────────────────────────────
  { territoryKey: "japan", power: PowerName.JAPAN, type: "INFANTRY", quantity: 3 },
  { territoryKey: "japan", power: PowerName.JAPAN, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "japan", power: PowerName.JAPAN, type: "FIGHTER", quantity: 3 },
  { territoryKey: "japan", power: PowerName.JAPAN, type: "BOMBER", quantity: 1 },
  { territoryKey: "japan", power: PowerName.JAPAN, type: "AA_GUN", quantity: 1 },
  { territoryKey: "japan", power: PowerName.JAPAN, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "manchuria", power: PowerName.JAPAN, type: "INFANTRY", quantity: 3 },
  { territoryKey: "manchuria", power: PowerName.JAPAN, type: "TANK", quantity: 1 },
  { territoryKey: "french_indo_china", power: PowerName.JAPAN, type: "INFANTRY", quantity: 4 },
  { territoryKey: "french_indo_china", power: PowerName.JAPAN, type: "ARTILLERY", quantity: 2 },
  { territoryKey: "french_indo_china", power: PowerName.JAPAN, type: "FIGHTER", quantity: 2 },
  { territoryKey: "french_indo_china", power: PowerName.JAPAN, type: "TANK", quantity: 2 },
  { territoryKey: "sz_36", power: PowerName.JAPAN, type: "BATTLESHIP", quantity: 1 },
  { territoryKey: "sz_36", power: PowerName.JAPAN, type: "CARRIER", quantity: 2 },
  { territoryKey: "sz_36", power: PowerName.JAPAN, type: "FIGHTER", quantity: 2 },
  { territoryKey: "sz_36", power: PowerName.JAPAN, type: "TRANSPORT", quantity: 2 },
  { territoryKey: "sz_44", power: PowerName.JAPAN, type: "DESTROYER", quantity: 1 },
  { territoryKey: "sz_44", power: PowerName.JAPAN, type: "TRANSPORT", quantity: 1 },
  { territoryKey: "sz_59", power: PowerName.JAPAN, type: "DESTROYER", quantity: 2 },
  { territoryKey: "sz_59", power: PowerName.JAPAN, type: "SUBMARINE", quantity: 1 },
  { territoryKey: "sz_60", power: PowerName.JAPAN, type: "BATTLESHIP", quantity: 1 },
  { territoryKey: "sz_60", power: PowerName.JAPAN, type: "CARRIER", quantity: 1 },
  { territoryKey: "sz_60", power: PowerName.JAPAN, type: "TRANSPORT", quantity: 2 },

  // ── USA ────────────────────────────────────────────────────────────────────
  { territoryKey: "eastern_us", power: PowerName.USA, type: "INFANTRY", quantity: 3 },
  { territoryKey: "eastern_us", power: PowerName.USA, type: "ARTILLERY", quantity: 1 },
  { territoryKey: "eastern_us", power: PowerName.USA, type: "FIGHTER", quantity: 1 },
  { territoryKey: "eastern_us", power: PowerName.USA, type: "BOMBER", quantity: 1 },
  { territoryKey: "eastern_us", power: PowerName.USA, type: "AA_GUN", quantity: 1 },
  { territoryKey: "eastern_us", power: PowerName.USA, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "western_us", power: PowerName.USA, type: "INFANTRY", quantity: 2 },
  { territoryKey: "western_us", power: PowerName.USA, type: "FIGHTER", quantity: 1 },
  { territoryKey: "western_us", power: PowerName.USA, type: "INDUSTRIAL_COMPLEX", quantity: 1 },
  { territoryKey: "sz_101", power: PowerName.USA, type: "BATTLESHIP", quantity: 1 },
  { territoryKey: "sz_101", power: PowerName.USA, type: "CARRIER", quantity: 1 },
  { territoryKey: "sz_101", power: PowerName.USA, type: "DESTROYER", quantity: 1 },
  { territoryKey: "sz_101", power: PowerName.USA, type: "TRANSPORT", quantity: 1 },
  { territoryKey: "sz_26", power: PowerName.USA, type: "BATTLESHIP", quantity: 1 },
  { territoryKey: "sz_26", power: PowerName.USA, type: "CARRIER", quantity: 1 },
  { territoryKey: "sz_26", power: PowerName.USA, type: "FIGHTER", quantity: 2 },
  { territoryKey: "sz_26", power: PowerName.USA, type: "DESTROYER", quantity: 1 },
  { territoryKey: "sz_26", power: PowerName.USA, type: "SUBMARINE", quantity: 1 },
  { territoryKey: "sz_26", power: PowerName.USA, type: "TRANSPORT", quantity: 2 },
];

// Starting IPC balances are defined in income.ts to avoid duplication.
// Import STARTING_IPC from "@aa/shared" (re-exported from income.ts).
